version: "3"

networks:
  neomdb_network:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - neomdb_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/dev_certs:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
      - client
    networks:
      - neomdb_network
  #nginx:
  #  image: nginx:stable-alpine
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - client
  #    - server
  #  networks:
  #    - neomdb_network

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - neomdb_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - database:db
    networks:
      - neomdb_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    depends_on:
      - database
    networks:
      - neomdb_network
    environment:
      - IS_PRODUCTION=true
      - DATABASE_HOST_PROD=database
      - DATABASE_PORT_PROD=3306

volumes:
  mysql:
