version: "3.8"
services:
  # The node-service needed for the development
  dev:
    image: node:18
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity

  # The mysql-service needed for the database
  mdb-container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  # The phpmyadmin-service needed for managing the database
  mdb-phpmyadmin-container:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - mdb-container:db

volumes:
  mysql:
