# This is the production docker-compose file
# It is used to deploy the application on the server with port 9000
# TODO: Current idea is, that the production build uses the database from plesk and not a container database like in development
# TODO: Check how how to access plesk database from the server container (host, port, password etc.)

version: "3.8"

networks:
  neomdb_network:
    driver: bridge

services:
  client:
    image: jbtit/neomdb:client-demo0.1.1
    networks:
      - neomdb_network

  server:
    image: jbtit/neomdb:server-demo0.1.1
    networks:
      - neomdb_network
    environment:
      IS_PRODUCTION: "true"
      ORIGIN_PROD: "${ORIGIN_PROD}"
      DB_PASSWORD_PROD_FILE: /run/secrets/db_neomdb_password
      DB_HOST_PROD: "${DB_HOST_PROD}"
      DB_PORT_PROD: "${DB_PORT_PROD}"
    secrets:
      - db_neomdb_password

  nginx-app:
    image: nginx:latest
    ports:
      - 9000:80
    depends_on:
      - client
      - server
    volumes:
      - ../nginx/default-app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - neomdb_network

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_neomdb_password:
    file: ./secrets/db_neomdb_password.txt
