# Only for local testing of the development and production builds
# This file should not be used in the production environment!

version: "3.8"

networks:
  neomdb_network:
    driver: bridge

services:
  client:
    image: jbtit/neomdb:client${CLIENT_VERSION}
    networks:
      - neomdb_network

  database:
    image: mysql
    ports:
      - 5306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - neomdb_network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password

  server:
    image: jbtit/neomdb:server${SERVER_VERSION}
    depends_on:
      - database
    networks:
      - neomdb_network
    environment:
      NODE_ENV: "production"
      ORIGIN_PROD: "${ORIGIN_PROD}"
      DB_PASSWORD_PROD_FILE: /run/secrets/db_neomdb_password
      DB_HOST_PROD: "${DB_HOST_PROD}"
      DB_PORT_PROD: "${DB_PORT_PROD}"
      ASSETS_PATH: "./assets"
      LOGS_PATH: "./logs"
    volumes:
      - ./assets:/app/assets
      - ./logs:/app/logs
    secrets:
      - db_neomdb_password

  nginx-app:
    image: nginx:latest
    ports:
      - 9002:80
    depends_on:
      - client
      - server
    volumes:
      - ../nginx/default-app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - neomdb_network

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_neomdb_password:
    file: ./secrets/db_neomdb_password.txt

volumes:
  mysql:
